<?php
return [
    'demographicsnames' => [
        'cameouk' => 'CAMEO UK Category',
        'cameoincome' => 'CAMEO Income Group',
        'cameoinvestor' => 'CAMEO Investor Group',
        'cameoproperty' => 'CAMEO Property Group',
        'cameofing' => 'CAMEO Financial Group',
        'ctaxband' => 'Property Council Tax Band',
        'priceindex' => 'Property Price Index'
    ],

    'userccjs' => [
        'CCJName' => 'Name',
        'CCJAddress' => 'Address',
        'CCJDOB' => 'DOB',
        'CourtName' => 'Court Name',
        'CaseNumber' => 'Case Number',
        'JudgementDate' => 'Judgement Date',
        'JudgementAmount' => 'Judgement Amount',
        'CCJStatus' => 'Status',
        'DateSatisfied' => 'Date Satisfied'
    ],

    'userShareFieldsNames' => [
        'Supplier_Type' => 'Supplier Type',
        'Account_Type' => 'Account Type',
        'Name' => 'Name',
        'Address' => 'Address',
        'DOB' => 'DOB',
        'Account_Start_Date' => 'Account Start Date',
        'Opening_Balance' => 'Opening Balance',
        'Latest_Balance' => 'Latest Balance',
        'Regular_Payment_Amount' => 'Regular Payment Amount'
    ],

    'asTypes' => [
        'ASLatestType',
        'ASLatestTypeRedOveride',
        'ASLatestTypeAAOveride',
        'ASLatestTypeAARedOveride'
    ],

    'asTypeColor' => [
        'Toxic' => 'red',
        'Default' => 'red',
        'Inert' => '#47d209',
        'Redemption' => '#47d209',
    ],

    'overRideTypes' => [
        'nooveride' => 'No Overide',
        'ignoretel' => 'Ignore Telecoms Only',
        'redemption' => 'Redemption Overide',
        'aa1overide' => 'AA1 Overide',
        'telredemp' => 'Ignore Telecoms & Redemption Overide',
        'telaa1' => 'Ignore Telecoms & AA1 Overide',
        'redempaa1' => 'Redemption Overide & AA1 Overide',
        'alloveride' => 'Overide All'
    ],

    'addressType' => [
        "C" => "Current",
        "P" => "Previous",
        "UI" => "Undeclared Intermediate",
        "UF" => "Undeclared Forwarding",
        "UP" => "Undeclared Previous",
        "UC" => "Undeclared Concurrent",
        "UM" => "Undeclared Miscellaneous",
        "UNKNOWN" => "Unknown",
    ],

    'extraFields' => [
        'reporttype',
        'minage',
        'maxage',
        'minloan',
        'maxloan',
        'totalactiveshareaccs_excl_tel',
        'percentactgreat6mthovertotal_excl_tel',
        'actsharegreaterthan6mnths_excl_tel',
        'percentactgreat12mthovertotal_excl_tel',
        'actsharegreaterthan12mnths_excl_tel',
        'autosearchmaxexceeded',
        'ageflag'
    ],

    'demoFields' => [
        'cameouk',
        'cameoincome',
        'cameoinvestor',
        'cameoproperty',
        'cameofing',
        'ctaxband',
        'priceindex'
    ],

    'incomeFields' => [
        'PrimaryIncome',
        'CompanyName',
        'EmployersPhone',
        'DirectDebit',
        'PayDayFreq',
        'NetMonthlyPay',
        'EmploymentLength',
        'NextPayDate'
    ],

    'costainOptions' => [
        'acceptable_levels_of_default_percent',
        'costain_minor_default_ratio',
        'costain_minor_default_ratio_excl_tel',
        'average_current_balance',
        'average_limit',
        'average_costain_value',
        'total_costain_value',
        'num_settled_accs_in_last_1month',
        'num_settled_accs_in_last_2month',
        'num_settled_accs_in_last_3month',
        'num_settled_accs_in_last_12months',
        'total_latest_balance',
        'total_regular_payment_amount',
        'TOTAL_average_current_balance',
        'TOTAL_average_limit',
        'TOTAL_average_costain_value',
        'TOTAL_total_costain_value',
        'historic_settle_ratio',
        'settle_to_active_tally',
        'affordability_ratio',
        'percentage_active_accs_unclassified',
        'num_family_members_at_home',
        'num_nonfamily_individuals_at_home'
    ],

    'costainMetricSummary' => [
        'accdef' => 'Level of Default (%)',
        'mindef' => 'Costain Minor Default Ratio',
        'mindefexcltel' => 'Costain Minor Default Ratio Excl. Tel, Bank, Building Society',
        'numset1month' => 'Number of Shares Settled in the last 1 month',
        'numset2month' => 'Number of Shares Settled in the last 2 month',
        'numset3month' => 'Number of Shares Settled in the last 3 month',
        'totlatbal' => 'Total Latest Balance',
        'totregpay' => 'Total Regular Payment Amount',
        'totavecurbal' => 'Total Average Current Balance',
        'totavelim' => 'Total Average Limit',
        'totavecosval' => 'Total Average Costain Value',
        'tottotcosval' => 'Total Total Costain Value',
        'hissetratio' => 'Historic Settle Ratio',
        'settoacttally' => 'Settle to Active Tally',
        'affordabilityratio' => 'Affordability Ratio',
        'peractaccsuncl' => 'Active Accounts Unclassified (%)',
        'numfamilymem' => 'Number of Family Members at home',
        'numnonfamilymem' => 'Number of Non-Family Individuals at home',
        'totcurbalt0' => 'Total Current Balance t0',
        'totcurbalt1' => 'Total Current Balance t1',
        'totcurbalt2' => 'Total Current Balance t2',
        'totcurbalt3' => 'Total Current Balance t3',
        'totcurbalt4' => 'Total Current Balance t4',
        'totcurbalt5' => 'Total Current Balance t5',
        'totcurbalt6' => 'Total Current Balance t6',
        'totcurbalt7' => 'Total Current Balance t7',

    ],

    'supplierTypeMap' => [
        'AF' => 'Agricultural Finance',
        'BF' => 'Bank Finance',
        'BK' => 'Bank',
        'BS' => 'Building Society',
        'CA' => 'Callcredit',
        'CB' => 'Credit Broker',
        'CC' => 'Credit Card Company',
        'CD' => 'CC Consumer Data Capture',
        'CU' => 'Credit Union',
        'DC' => 'Debt Collection Agency',
        'ED' => 'EuroDirect',
        'FC' => 'Factoring',
        'FH' => 'Finance Housing',
        'FN' => 'Finance House',
        'GO' => 'Government',
        'HC' => 'Home Credit',
        'HS' => 'Home Shopping',
        'IN' => 'Insurance Company',
        'IT' => 'Internet/On Line Service',
        'LS' => 'Leasing Company',
        'MC' => 'Mortgage Company',
        'MF' => 'Motor Vehicle Finance Company',
        'MO' => 'Mail Order',
        'RC' => 'Rental Company',
        'RT' => 'Retailer',
        'SC' => 'Securities',
        'SL' => 'Student Loan',
        'ST' => 'Stockbroker',
        'TC' => 'Telecommunications Supplier',
        'UT' => 'Utility',
        'VR' => 'Vehicle Rental',
        'XX' => 'Unknown'
    ],

    'accTypeMap' => [
        'AD' => 'Asset Discounting',
        'AF' => 'Agricultural Finance',
        'AM' => 'Airtime Agreement - mthly contract',
        'AU' => 'Airtime Agreement - upfront',
        'BA' => 'Balloon Repayment Loan',
        'BC' => 'Book/Music/Video club',
        'BD' => 'Budget Account',
        'BH' => 'Balloon HP',
        'BI' => 'Buildings Insurance',
        'BK' => 'Bank',
        'BL' => 'Unsecured Business Loan',
        'BM' => 'Residential Buy to Let',
        'BN' => 'Buy Now Pay Later',
        'BO' => 'Broadband',
        'BR' => 'Brewery Loan',
        'BU' => 'Business Line',
        'BX' => 'Builders Merchant Credit',
        'CA' => 'Current Account',
        'CB' => 'Cable',
        'CC' => 'Credit Card',
        'CD' => 'Crown Debt',
        'CH' => 'Charge Card',
        'CI' => 'Contents Insurance',
        'CM' => 'Commercial Mortgage',
        'CO' => 'Company Credit Card (individual responsible for debt)',
        'CP' => 'Personal Contract Purchase',
        'CR' => 'Consumer Goods Rental',
        'CS' => 'Unsecured Car Loan',
        'CT' => 'Council Tax',
        'CX' => 'Credit Sale',
        'CY' => 'Conditional Sale',
        'CZ' => 'Combined Credit Account',
        'DA' => 'Consolidated Debt',
        'DC' => 'Debit Card',
        'DF' => 'Bank Default',
        'DH' => 'Deferred HP',
        'DM' => 'Shared Ownership Mortgage (Housing Association)',
        'DP' => 'Deferred payment',
        'DU' => 'Dual Fuel',
        'EC' => 'E-Cash',
        'ED' => 'Education',
        'EE' => 'Electricity - even payment',
        'EL' => 'Employer Loan',
        'EW' => 'Water - even payment',
        'FC' => 'Fuel Card (individual responsible for debt)',
        'FD' => 'Fixed Term Deferred Payment loan',
        'FL' => 'Finance Lease',
        'FM' => 'Flexible Mortgage',
        'FO' => 'Residential First Mortgage with Investment Offset',
        'FS' => 'Further Secured Loan',
        'FT' => 'Factoring',
        'GA' => 'Gambling',
        'GE' => 'Gas - even payment',
        'GI' => 'General Insurance',
        'GL' => 'Guarantee Liability',
        'HA' => 'Home Shopping Agency',
        'HC' => 'Home Credit',
        'HD' => 'Home Shopping Direct',
        'HI' => 'Household Insurance',
        'HP' => 'Hire Purchase',
        'HS' => 'Home Shopping',
        'HX' => 'Home Shopping Cash',
        'IC' => 'Internet Credit Line',
        'IL' => 'Advance Against Income',
        'IM' => 'Residential Second Mortgage with Investment Offset',
        'IN' => 'Insurance',
        'IS' => 'Internet Shopping',
        'LN' => 'Loan (unspecified type)',
        'LP' => 'Life Policy Loan',
        'LR' => 'Local Rates - even payment scheme',
        'LS' => 'Lease',
        'LT' => 'Landline Telephone - even payment',
        'MA' => 'Mail Order Agency',
        'MC' => 'Multifunctional Card',
        'MG' => 'Mortgage (unspecified type)',
        'MI' => 'Motor Insurance',
        'ML' => 'Motor Finance Loan - General',
        'MM' => 'Semi-commercial first mortgage',
        'MO' => 'Mail Order',
        'MP' => 'Mortgage Protection',
        'MT' => 'Mortgage and Unsecured Loan',
        'MU' => 'Multi Communications',
        'NM' => 'Semi-commercial second mortgage',
        'OA' => 'Option Account',
        'OD' => 'Overdraft',
        'OI' => 'Oil',
        'OL' => 'Operating Lease',
        'OM' => 'Investment Off Set Mortgage',
        'OR' => 'Other Rental',
        'PI' => 'Personal Health Insurance',
        'PL' => 'Petroleum Loan',
        'PP' => 'Payment Protection',
        'PR' => 'Property Rental',
        'PT' => 'Card Protection',
        'QA' => 'Airtime Agreement - qtly payment',
        'QE' => 'Electricity - qtly payment',
        'QG' => 'Gas - qtly payment',
        'QT' => 'Landline Telephone - qtly payment',
        'QU' => 'Utility - qtly payment',
        'QW' => 'Water - qtly payment',
        'RC' => 'Revolving credit',
        'RG' => 'Repayment Grant',
        'RM' => 'Residential Mortgage',
        'RQ' => 'Returned Cheque',
        'RS' => 'Retail Store Card',
        'RT' => 'Rental Agreement (General)',
        'SA' => 'Stock broking Account',
        'SB' => 'Secured Business Loan',
        'SC' => 'Secured Car Loan',
        'SE' => 'Secured Loan',
        'SL' => 'Student Loan',
        'SM' => 'Residential Second Mortgage',
        'SO' => 'Set Off Loan',
        'SI' => 'Satellite',
        'SS' => 'Stationery Supplier',
        'ST' => 'Store Card',
        'SX' => 'Set Off Current Account (if set off against mortgage then use FO or IM)',
        'TL' => 'Term Loan',
        'TM' => 'Telecommunications Supplier',
        'TR' => 'Trade Credit',
        'TV' => 'TV Shopping',
        'UE' => 'Utility - even payment',
        'UL' => 'Unsecured Loan',
        'UT' => 'Utility',
        'VS' => 'Variable Subscription',
        'WI' => 'Weekly Installment Plan',
        'XM' => 'Residential First Time Buyer',
        'ZC' => 'Standby Credit',
        'ZH' => '0% HP',
        'ZL' => '0% Finance Loan',
        'ZM' => '100+% LTV Mortgage',
        'XX' => 'Unknown'
    ],

];
